=== jedi-academy/example-xml-models/2-vehicle-centric/data/sales05-vehicle.dtd
<!--
DTD for sales05-vehicle.xml.
The data is hierarchical, structured by vehicle type

COMP4711 Fall 2011
Lab solution
-->

<!-- The root element, which should contain multiple *vehicles* elements.
The data comes from Industry Canada, and is for 2010.
There could be more data, and past data, so it makes sense to constrain 
the year attribute.
 -->
<!ELEMENT sales (vehicles)+>
<!ATTLIST sales
    year (2009|2010|2011|2012) #REQUIRED
  >

<!-- Each vehicles element contains the source data
for a single vehicle type, and nested source elements,
one for each of the countries in North America -->
<!ELEMENT vehicles (source)*>
<!ATTLIST vehicles
    type (car|light|heavy) #REQUIRED
  >

<!--- A source element contains the sales data, by quarter,
for a single country -->
<!ELEMENT source (sold)*>
<!ATTLIST source
    country (canada|mexico|usa) #REQUIRED
  >

<!--- A sold element contains the number of vehicles sold
of a given type in a single country, during a specific quarter -->
<!ELEMENT sold (#PCDATA)>
<!ATTLIST sold
    quarter (1|2|3|4) #REQUIRED
  >

=== jedi-academy/example-xml-models/2-vehicle-centric/data/sales05-vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales SYSTEM "sales05-vehicle.dtd">
<!--
    Document   : sales05-vehicle.xml
    Created on : October 11, 2011, 11:18 PM
    Author     : jim
    Description:
        North America Sales for 2010, modeled by vehicle type.
        This is one perspective, of many possible.
-->

<sales year="2010">
    <vehicles type="car">
        <source country="canada">
            <sold quarter="1">148111</sold>    
            <sold quarter="2">212570</sold>    
            <sold quarter="3">183850</sold>    
            <sold quarter="4">149818</sold>    
        </source>
        <source country="mexico">
            <sold quarter="1">114361</sold>    
            <sold quarter="2">110277</sold>    
            <sold quarter="3">119881</sold>    
            <sold quarter="4">155048</sold>    
        </source>
        <source country="usa">
            <sold quarter="1">1282671</sold>    
            <sold quarter="2">1542192</sold>    
            <sold quarter="3">1468936</sold>    
            <sold quarter="4">1341634</sold>    
        </source>
    </vehicles>
    <vehicles type="light">
        <source country="canada">
            <sold quarter="1">178831</sold>    
            <sold quarter="2">245813</sold>    
            <sold quarter="3">235473</sold>    
            <sold quarter="4">200234</sold>    
        </source>
        <source country="mexico">
            <sold quarter="1">74033</sold>    
            <sold quarter="2">70960</sold>    
            <sold quarter="3">74835</sold>    
            <sold quarter="4">99109</sold>    
        </source>
        <source country="usa">
            <sold quarter="1">1255913</sold>    
            <sold quarter="2">1520199</sold>    
            <sold quarter="3">1528261</sold>    
            <sold quarter="4">1614712</sold>    
        </source>
    </vehicles>
    <vehicles type="heavy">
        <source country="canada">
            <sold quarter="1">5867</sold>    
            <sold quarter="2">7462</sold>    
            <sold quarter="3">7343</sold>    
            <sold quarter="4">8016</sold>    
        </source>
        <source country="mexico">
            <sold quarter="1">5129</sold>    
            <sold quarter="2">7067</sold>    
            <sold quarter="3">7772</sold>    
            <sold quarter="4">8409</sold>    
        </source>
        <source country="usa">
            <sold quarter="1">51124</sold>    
            <sold quarter="2">52892</sold>    
            <sold quarter="3">53992</sold>    
            <sold quarter="4">59694</sold>    
        </source>
    </vehicles>
</sales>
