=== jedi-academy/example-xml-models/3-table-centric/data/sales05-table.dtd
<!--
DTD for sales05-table.xml

The data is like a single table in a relational database.

COMP4711 Fall 2011
Lab solution
-->

<!-- The root element contains multiple sold elements, each of which is like a 
cell in a worksheet. Each such document is for a specific year.
 -->
<!ELEMENT sales (sold)+>
<!ATTLIST sales
    year (2009|2010|2011|2012) #REQUIRED
  >

<!--- A sold element contains the number of vehicles sold
of a given type in a single country, during a specific quarter -->
<!ELEMENT sold (#PCDATA)>
<!ATTLIST sold
    country (canada|mexico|usa) #REQUIRED
    type (car|light|heavy) #REQUIRED
    quarter (1|2|3|4) #REQUIRED
  >

=== jedi-academy/example-xml-models/3-table-centric/data/sales05-table.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales SYSTEM "sales05-table.dtd">
<!--
    Document   : sales05-source.xml
    Created on : October 11, 2011, 11:18 PM
    Author     : jim
    Description:
        North America Sales for 2010, modeled like a spreadsheet, kinda.
        This is one perspective, of many possible.
-->

<sales year="2010">
    <sold country="canada" type="car" quarter="1">148111</sold>    
    <sold country="canada" type="car" quarter="2">212570</sold>    
    <sold country="canada" type="car" quarter="3">183850</sold>    
    <sold country="canada" type="car" quarter="4">149818</sold>    
    <sold country="canada" type="light" quarter="1">178831</sold>    
    <sold country="canada" type="light" quarter="2">245813</sold>    
    <sold country="canada" type="light" quarter="3">235473</sold>    
    <sold country="canada" type="light" quarter="4">200234</sold>    
    <sold country="canada" type="heavy" quarter="1">5867</sold>    
    <sold country="canada" type="heavy" quarter="2">7462</sold>    
    <sold country="canada" type="heavy" quarter="3">7343</sold>    
    <sold country="canada" type="heavy" quarter="4">8016</sold>    
    <sold country="mexico" type="car" quarter="1">114361</sold>    
    <sold country="mexico" type="car" quarter="2">110277</sold>    
    <sold country="mexico" type="car" quarter="3">119881</sold>    
    <sold country="mexico" type="car" quarter="4">155048</sold>    
    <sold country="mexico" type="light" quarter="1">74033</sold>    
    <sold country="mexico" type="light" quarter="2">70960</sold>    
    <sold country="mexico" type="light" quarter="3">74835</sold>    
    <sold country="mexico" type="light" quarter="4">99109</sold>    
    <sold country="mexico" type="heavy" quarter="1">5129</sold>    
    <sold country="mexico" type="heavy" quarter="2">7067</sold>    
    <sold country="mexico" type="heavy" quarter="3">7772</sold>    
    <sold country="mexico" type="heavy" quarter="4">8409</sold>    
    <sold country="usa" type="car" quarter="1">1282671</sold>    
    <sold country="usa" type="car" quarter="2">1542192</sold>    
    <sold country="usa" type="car" quarter="3">1468936</sold>    
    <sold country="usa" type="car" quarter="4">1341634</sold>    
    <sold country="usa" type="light" quarter="1">1255913</sold>    
    <sold country="usa" type="light" quarter="2">1520199</sold>    
    <sold country="usa" type="light" quarter="3">1528261</sold>    
    <sold country="usa" type="light" quarter="4">1614712</sold>    
    <sold country="usa" type="heavy" quarter="1">51124</sold>    
    <sold country="usa" type="heavy" quarter="2">52892</sold>    
    <sold country="usa" type="heavy" quarter="3">53992</sold>    
    <sold country="usa" type="heavy" quarter="4">59694</sold>    
</sales>
